image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  when: manual
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

eslint:
  stage: test
  script: ./node_modules/eslint/bin/eslint.js . --fix